{
 "title": "Error/Warning Tracker",
 "description": "Log parsing example",
 "time": { "from": "now/y", "to": "now" },
 "panels": [
  {
   "title": "Latest Run Warning Count",
   "type": "table",
   "description": "See warnings from the latest run",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\nname as \"Name\",\n(\n  CASE\n  WHEN name = '1_1_yosys.log' THEN (\n    CASE\n    WHEN log ~ 'unsupported expression' THEN 'INVALID_STDCELL_EXPR'\n    ELSE 'SYN_MISC_WARN'\n    END\n  )\n  ELSE 'MISC_WARN'\n  END \n) as \"Type\",\nCOUNT(*) as \"Count\"\nFROM logs\nWHERE log ~* '^.?warn.*' AND log !~* '^Warnings:'\nGROUP BY \"Name\", \"Type\""
    }
   ]
  },
  {
   "title": "Latest Run Warnings",
   "type": "table",
   "description": "See warnings from the latest run",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\nname as \"Name\",\nlog as \"Log\",\n(\n  CASE\n  WHEN name = '1_1_yosys.log' THEN (\n    CASE\n    WHEN log ~ 'expression' THEN 'INVALID_STDCELL_EXPR'\n    ELSE 'SYN_MISC_WARN'\n    END\n  )\n  ELSE 'MISC_WARN'\n  END \n) as \"Type\"\nFROM logs\nWHERE log ~* '^.?warn.*' AND log !~* '^Warnings:'\nLIMIT 1000;"
    }
   ]
  },
  {
   "title": "Latest Run Errors",
   "type": "table",
   "description": "See errors from the latest run",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT name as \"Log File\", log as \"Error\" FROM logs WHERE log ~* '^.?error.*'"
    }
   ]
  },
  {
   "title": "Latest Run Errors",
   "type": "table",
   "description": "See errors from the latest run",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT name as \"Log File\", log as \"Error\" FROM logs WHERE log ~* '^.?error.*'"
    }
   ]
  }
 ]
}