{
 "title": "Run Metrics Trend",
 "description": "Snapshot of run metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Timing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "WNS vs. Run",
   "type": "graph",
   "description": "Worst Negative Slack",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  -1 * value as \"WNS\",\n  time\nFROM metrics\nWHERE\n  metric = 'wns'"
    }
   ]
  },
  {
   "title": "TNS vs. Run",
   "type": "graph",
   "description": "Total Negative Slack",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  -1 * value as \"TNS\",\n  time\nFROM metrics\nWHERE\n  metric = 'tns'"
    }
   ]
  },
  { "title": "Power & Area", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Power Breakdown vs. Run",
   "type": "graph",
   "description": "Shows the power breakdown by component and dissipation type.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  metric,\n  value,\n  time\nFROM metrics\nWHERE\n  SPLIT_PART(metric, '_', 1) = 'power'"
    }
   ]
  },
  {
   "title": "Area vs. Run",
   "type": "graph",
   "description": "Standard cell area within design",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "µm²" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  value,\n  time\nFROM\n  metrics\nWHERE\n  metric = 'area'\n"
    }
   ]
  }
 ]
}